# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "31df2f6ccd03151c1168988807e67a1f"
name = "theme app extesion demo"
handle = "theme-app-extesion-demo"
application_url = "https://capacity-idle-arrangements-closely.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tejas-checkout-extension.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_script_tags,write_content,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://capacity-idle-arrangements-closely.trycloudflare.com/auth/callback",
  "https://capacity-idle-arrangements-closely.trycloudflare.com/auth/shopify/callback",
  "https://capacity-idle-arrangements-closely.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
